all:
  hw16:
  
wh16:
  hosts:
    nginx:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_ssh_private_key_file: /home/novoselov/homework-linux/16_log/.vagrant/machines/nginx/virtualbox/private_key
    log:
      ansible_host: 127.0.0.1
      ansible_port: 2200
      ansible_ssh_private_key_file: /home/novoselov/homework-linux/16_log/.vagrant/machines/log/virtualbox/private_key