# -*- mode: ruby -*-
# vi: set ft=ruby :
Mashines = {
    :r1 => {
#	:box_name => "centos/7",
#	:ip_addr => '172.20.10.10',
    },
    :r2 => {
#	:box_name => "centos/7",
#	:ip_addr => '172.20.10.20',
    },
    :r3 => {
#	:box_name => "centos/7",
#	:ip_addr => '172.20.10.30',
    },
}

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.box_version = "2004.01"
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 256
      v.cpus = 1
    end
  
    config.vm.define "r1" do |r1|
      r1.vm.network "private_network", ip: "172.20.10.10"
      r1.vm.network "private_network", ip: "10.10.10.1", virtualbox__intnet: "net1"
      r1.vm.network "private_network", ip: "10.10.30.1", virtualbox__intnet: "net3"
      r1.vm.hostname = "r1"
    end
  
    config.vm.define "r2" do |r2|
      r2.vm.network "private_network", ip: "172.20.10.20"
      r2.vm.network "private_network", ip: "10.10.10.2", virtualbox__intnet: "net1"
      r2.vm.network "private_network", ip: "10.10.20.1", virtualbox__intnet: "net2"
      r2.vm.hostname = "r2"
    end
  
    config.vm.define "r3" do |r3|
      r3.vm.network "private_network", ip: "172.20.10.30"
      r3.vm.network "private_network", ip: "10.10.20.2", virtualbox__intnet: "net2"
      r3.vm.network "private_network", ip: "10.10.30.2", virtualbox__intnet: "net3"
      r3.vm.hostname = "r3"
    end

    config.vm.provision "shell", inline: <<-SHELL
    mkdir -p ~root/.ssh
    cp ~vagrant/.ssh/auth* ~root/.ssh
    sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
    sudo yum install -y epel-release
    sudo yum install -y ansible
    name=`hostname`
    SHELL

    config.vm.provision :ansible do |ansible|
    ansible.inventory_path = "inventories/hosts.yml"
    ansible.limit = $name
        ansible.playbook = "stand.yml"
    end	
  
  end